development: &development
  adapter: postgresql
  database: genuineblue_development
  encoding: utf8
test:
  <<: *development
  database: genuineblue_test
production:
  <<: *development
  database: genuineblue_production
staging:
  <<: *development
  database: genuineblue_staging
